version: '2'

services:

  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssw0rd
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
    links:
      - db
    volumes:
      - ./nextcloud/config:/config 
      - ./nextcloud/data:/data 
    environment:
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

volumes:
  nextcloud:
  db:      